### ISSUE TITLE
Sign editing and protection

### ISSUE THREAD

**Issue by Sir-Will** [AlexMason/BetterCommandSigns#2]
hey,

there are few mods which add the ability to edit signs with right clicking them. GP prevents this in protected areas but unfortunately it does also prevent BCS.

Do you know any solution for that?

**Comment by AlexMason** [comment]
Unfortunately you will have to allow sign interact to allow Grief Prevention to allow BCS signs.  The downside to this is making all your signs editable with said mod.  

I fixed this issue in the newest release https://github.com/AlexMason/BetterCommandSigns/releases/tag/0.0.4
